### ISSUE TITLE
No manifest file

### ISSUE THREAD

**Issue by PostalMike** [DNNCommunity/DNN.Reports#11]
I'm not sure if the module will work on DNN 9 but got an error trying to install the extension.

Looking over the zip file, there is no manifest which would cause this issue.

With the DNN 7 version there are many SQL errors coming up where parameters are undefined but are used by the queries.  Has this issue been fixed?  If not I'll forward what I found a few years back and got no answers to.

Will your module work on DNN 9?

Thanks,

Mike Durthaler

**Comment by EPTamminga** [comment]
I just installed the most current DNNReports (05.07.01) on a clean DNN 9.1.1 install and could run reports without a problem. The is a manifest file in the install zip (Reports.dnn). See the releases tab here in this repo,  https://github.com/DNNCommunity/DNN.Reports/releases/tag/05.07.01.
If the error log contains DNNReport errors, it is mostly due to the fact that the DNN search indexer runs the report behind the scenes, when there is no context of portal or user.  Just disable the DNN search indexing for the module instance (Module Settings. Advanced Settings, Allow Indexing: Off).

**Comment by PostalMike** [comment]
Still getting about 84 of these errors a day, for the different instances of the Reports module on all pages.  We have 5 or 6 instances of it.

I had thought unchecking Allow Indexing fixed it.  It doesn't.

AssemblyVersion:7.2.1

PortalID:-1

PortalName:

UserID:-1

UserName:

ActiveTabID:-1

ActiveTabName:

RawURL:

AbsoluteURL:

AbsoluteURLReferrer:

UserAgent:

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:9d1f5329-9166-489e-a87a-b74e52f94248

InnerException:There is an error in your SQL at line 26: Must declare the scalar variable "@UserId". Must declare the scalar variable "@PortalId". Must declare the scalar variable "@PortalId". Incorrect syntax near the keyword 'ELSE'.

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:DotNetNuke.Modules.Reports.DataSources.DotNetNuke.DotNetNukeDataSource.ExecuteSQLReport

StackTrace:

Message:

DotNetNuke.Modules.Reports.Exceptions.DataSourceException: There is an error in your SQL at line 26: Must declare the scalar variable "@UserId".
Must declare the scalar variable "@PortalId".
Must declare the scalar variable "@PortalId".
Incorrect syntax near the keyword 'ELSE'.
   at DotNetNuke.Modules.Reports.DataSources.DotNetNuke.DotNetNukeDataSource.ExecuteSQLReport()
   at DotNetNuke.Modules.Reports.DataSources.SqlDataSourceBase.ExecuteReport(ReportInfo report, PortalModuleBase hostModule, IDictionary`2 inputParameters)
   at DotNetNuke.Modules.Reports.ReportsController.ExecuteReport(ReportInfo objReport, String cacheKey, Boolean bypassCache, PortalModuleBase hostModule, Boolean& fromCache)
   at DotNetNuke.Modules.Reports.ReportsController.ExecuteReport(ReportInfo objReport, String cacheKey, Boolean bypassCache, PortalModuleBase hostModule)
   at DotNetNuke.Modules.Reports.ReportsController.GetSearchItems(ModuleInfo ModInfo)
   at DotNetNuke.Services.Search.ModuleIndexer.GetSearchIndexItems(Int32 portalId)
Source:

Server Name: IIS2104

**Comment by PostalMike** [comment]
Also ... where is the zip install for the module?  I tried downloading the release, it won't install.

I can't find the module zip, only the Development and Release zips.

Thanks!

**Comment by EPTamminga** [comment]
The error is still related to running the reporting module without user/portal context in combination with a schedule that executes the report. Try disabling all schedules in the host menu, clear the error log and see if it still happens.

**Comment by EPTamminga** [comment]
A release .zip is the installable module. All releases are in the releases tab of the repository here. 
Version 05.07.01 is the latest release
https://github.com/DNNCommunity/DNN.Reports/releases/tag/05.07.01
If you want to develop on the source code yourself, clone the repository.

**Comment by PostalMike** [comment]
EP,

I have created a file with additional info for you.  Apparently your module picks up known Portal Module Base items such as UserId, PortalId, ModuleId and so on.  So, when SQL Parameters such as @UserId, @PortalId and @ModuleId are used, it knows 'Aha ... I'll go snag that ...' and then does so.

But, the Scheduler doesn't see it declared so fires an error.  But when it's declared and tested in Settings the error comes up that it is already declared and parameter names in Stored Procedures must be unique.

Please find the file with the screen shots attached.

I'm wondering if a setting / code can be added to disable automatic DNN variable detection, if that's what it's called and allow other developers to customize.  This will allow declaration of the parameters, allow them to be passed, etc. and then not throw the scheduler errors.  Better yet ... let's tell the scheduler 'ignore me in these cases' or some such?

Thanks,

Mike Durthaler

[SQL Parameter Errors.docx](https://github.com/DNNCommunity/DNN.Reports/files/1735201/SQL.Parameter.Errors.docx)

**Comment by EPTamminga** [comment]
Good morning Mike,

Thank you for figuring out what's wrong. With this info it is easier to find a solution. I will set up a new dev environment and try to find a way around it.

**Comment by PostalMike** [comment]
FYI EP,

Replying directly to the email I get in my Outlook doesn't work.  Also, see the entire reply.  Nearly 2 years ago I tried to reach out via DNN forums and never heard back.

This info is not true but it might be a Git Hub issue.

_You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread._ 

Here is what I just tried to email you from my Outlook account:

Perfect.

FYI – I did write up a request via DNN Site nearly 2 years ago.  Obviously I was not aware you were on Git Hub or would have gotten this info to you quickly.

Now … another question if I might.  How does one configure a date range for the report?  I could hack the grid visualizer to put a drop down or a date picker but I was hoping this had been accounted for and I’d just overlooked it.

I do have customizations, by the way, to have different layouts by altering the VB code of the Grid Visualizer and you might like these.  I’ve need to customize a totals row, hide certain columns for a report from certain users, etc. and worked around the logic to do so.

I could push these up to you and have wanted to for some time but never heard back from the posts made via the DNN Software Community Forums.  You might also have others on the Community Forums who have not figured out you’re alive and well on Git Hub.

I will update my posts there as I get time and info you.  Should I use the reply to above?

Thanks,

Michael Durthaler
3690 Easton Loop W.
Columbus, OH 43219
mdurthaler@sbcglobal.net 
740 739 4498 – Home
740 739 3765 – Cell

**Comment by PostalMike** [comment]
Darn ... the link to the reports module release page didn't work for me either from Outlook but it worked when I clicked on it here.

Sure enough, just verified it.  Clicked on it from this page and it worked.  Clicked on the same link in Outlook and it took me to Git Hub's 404 page. 

Not sure why that would be.  Where would I report this?

Thanks!

Mike

**Comment by EPTamminga** [comment]
Can it have something to do with filtering of Outlook?

Can you show the exact link that is presented in your Outlook email message?

And compare that with the link in the browser here?
`https://github.com/DNNCommunity/DNN.Reports/releases/tag/05.07.01`

**Comment by PostalMike** [comment]
EP, 

I'm not sure of how parameters are supposed to be added.  I'm trying to add in a date range, crossing my fingers that the module creates the UI parts.  The documentation implies this is the case:

![image](https://user-images.githubusercontent.com/13373285/37061869-d22d7680-2162-11e8-9cfd-812058d0abc7.png)

Here is what the manual says to do, at the end of page 8 and continuing on page 9:

To allow users to extend the Reports module queries a simple URL parameter system has been added which allows users to provide a list of QueryString parameters which will be added to the query. The parameter names are in the following format: @url_[QueryString Parameter Name]. Only the parameters specified in the "Allowed URL Parameters" section will be added. In the Allowed URL Parameters field add a comma separated list of 

URL QueryString parameters which can be used in the query. URL Parameter names will be prefixed with "url_", plus any data source specific prefix (such as "@" for SQL Server).

I'll have to add something into the module but I'm hoping I've just got the instructions misunderstood.

If what I'm thinking isn't what the instructions mean, enlighten me.

Thanks,

Mike

**Comment by EPTamminga** [comment]
@PostalMike I do not know all details of the Reports module myself (I am not the author, just the person that moved the module to GitHub and did some enhancements), so I will have to create a test environment and experiment a bit to see if I can help you.

**Comment by PostalMike** [comment]
EP, thanks for the email.

I can't reply directly to it.  Please reach out to me directly at mdurthaler@sbcglobal.net. 

Here is what comes through, the notifications for Git allows a reply but somehow the DNN Community email takes over and doesn't allow a reply.

I am willing to help, just let me know.

I’ve had to hack the VB code behind files to do anything, really, to get individual instances of the module for different purposes.  I’d anticipate I’ll have to do that to put parameters on the HTML page which interact with the module code.

When I get home from my day job, it’s well past your bed time over there in Eastern Europe Time.  But I’d be willing to get up early on a Saturday / Sunday to collaborate and come up with something.  Sounds like you know the code a bit better than I.

Let me know if that would work.

**Comment by EPTamminga** [comment]
Replaced the search indexing routines in DNN reports version 6.0.0, so the search indexing schedule should not generate errors anymore

**Comment by PostalMike** [comment]
Great news.  Not sure why I could not respond directly from email but that didn't work.

I need to add a drop down parameter to filter by username.  There's an implied way to do it but it doesn't seem to work.

If you'll be around over the weekend, I'll be picking away at it.  Otherwise by the time I'm home from my day job at 15:30 it's something like 20:30 or 21:30 your time, not much of a way to hook up during the week.  Would love to make the module more flexible.

Thanks,

Mike
