### ISSUE TITLE
Error using Intall Extension Wizard - DNN 8.0.4

### ISSUE THREAD

**Issue by boct** [DNNCommunity/DNN.Reports#12]
Message:Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 1, position 5.

StackTrace:

InnerMessage:Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 1, position 5.

**Comment by EPTamminga** [comment]
I just downloaded the latest DNN.Reports version [Reports_05.07.01_Install.zip](https://github.com/DNNCommunity/DNN.Reports/releases/download/05.07.01/Reports_05.07.01_Install.zip) and installed it without any problem in a clean DNN8 site.

What are you trying to do that goes wrong?

**Comment by EPTamminga** [comment]
No reaction. Issue closed
