### ISSUE TITLE
Razor visualizer

### ISSUE THREAD

**Issue by EPTamminga** [DNNCommunity/DNN.Reports#20]
Tip from Jeremy Farrance in the DNN forums: a Razor visualizer.

Here is what is left of the original projects. https://archive.codeplex.com/?p=razorreports
**Attached to this issue**
[RazorReports.zip Codeplex Archive](https://github.com/DNNCommunity/DNN.Reports/files/1973467/RazorReports.zip)

There is also this, but I am not even sure it is the same or similar. https://github.com/2sic/Razor-Visualizer-for-Dnn-Reports
**To be found here on GitHub**

**Comment by Mark-89** [comment]
Now solved in: https://github.com/DNNCommunity/DNN.Reports/pull/27
