### ISSUE TITLE
Can reports module display profile picture?

### ISSUE THREAD

**Issue by wuffpack** [DNNCommunity/DNN.Reports#5]
I'm using the reports module to display information about users that are in selected DNN Roles.   it makes a nice way to keep up with who is in what role.. and other users can see who they can call on.   Is there a way to show their profile photo in addition to just their name?  

The SQL looks something like this..
`SELECT 
u.LastName + ', ' + u.FirstName AS [Name],
upd.City
FROM dbo.Users as u INNER JOIN
dbo.UserRoles AS ur ON u.UserID = ur.UserID  INNER JOIN
dbo.Roles AS r ON ur.RoleID = r.RoleID
AND ur.ExpiryDate >= getdate()
LEFT OUTER JOIN
(SELECT       
up.UserID,   
MAX(CASE WHEN ppd.PropertyName = 'City' THEN up.PropertyValue ELSE '' END) AS City
FROM            
dbo.UserProfile AS up INNER JOIN  
dbo.ProfilePropertyDefinition AS ppd ON up.PropertyDefinitionID = ppd.PropertyDefinitionID    GROUP BY up.UserID) AS upd ON u.UserID = upd.UserID  
WHERE r.RoleName = 'some_role_name' ORDER BY u.lastname`

**Comment by sleupold** [comment]
you should be able to join from user profile to vw_files to obtain filepath of the picture.

**Comment by sleupold** [comment]
PS: another option would be using bbimagehandler

**Comment by wuffpack** [comment]
Challenges come in many forms.   To me, it's spelled DNN.

Thanks. I'll look into this.

Regards,

Kevin Blackwood

On Sun, Jun 19, 2016 at 5:11 PM, Sebastian Leupold <notifications@github.com

**Comment by sleupold** [comment]
check out http://bbimagehandler.codeplex.com/, once you install BBImageHandler,
you may retrieve the user image by using 
`< img src="bbimagehandler.ashx?dnn=1&userid=7&portalid=0&height=150" / > 
in your reports module (replace userid with record value)
