### ISSUE TITLE
Why do I need to use IIS to create a virtual directory named "Reports" in order for the module to function?  And how can I create a virtual directory using DNN (in the case of a website I cannot use IIS on)?

### ISSUE THREAD

**Issue by langkd** [DNNCommunity/DNN.Reports#51]

**Comment by langkd** [comment]
Why do I need to use IIS to create a virtual directory named "Reports" in order for the Reports module to function? And how can I create a virtual directory using DNN (in the case of a website I cannot use IIS on)?

**Comment by valadas** [comment]
I do not use this module a lot but I am not aware you need to create a virtual directory, I have also not seen any mention in the docs to create a virtual directory, can you explain why you are creating this? @langkd

**Comment by david-poindexter** [comment]
That is not a valid requirement.  Perhaps this issue can be closed?

**Comment by EPTamminga** [comment]
A virtual IIS directory is not needed, DNN.Reports works as a standard DNN module without special requirements
