### ISSUE TITLE
caching setting in module setting not working

### ISSUE THREAD

**Issue by lilcontreras** [DNNCommunity/DNN.Reports#53]
Caching setting in module settings isn't saving and module settings always triggers an error in the console when loading

1. Go to Module Setting
2. Open console in browser's developer tools
3. Error automatically says "ReferenceError: dnn_reports_showHideByCheckbox is not defined"
4. Try to check the "Caching" checkbox and the setting associated with this doesn't load. Therefore you can't save that setting.

If you check the "Caching" checkbox, you should get "Cache the data for <<textbox>> minutes.

No errors reported in the Admin Logs

Using Reports v. 6.1.0 on DNN 9.2.2

**Comment by EPTamminga** [comment]
Have to review/reproduce before close
