### ISSUE TITLE
Anyone tested this module with the latest 9.3.2 DNN  version?

### ISSUE THREAD

**Issue by Audun1555** [DNNCommunity/DNN.Reports#54]
Hi, just upgraded to 9.3.2 - and when I try to update the reportsmodule it fails during installation. Seems like it cannot extract resources.zip - is this due to the breaking changes in 9.2 in regards to new assembliname on the zip lib that is used? Or have I stumbeled upon another error in DNN 9.3.2?

https://www.dnnsoftware.com/community-blog/cid/155518/dnn-920-and-sharpziplib-breaking-change

Thanks for any help!

//Audun

**Comment by jncraig** [comment]
I just installed Reports 6.1.0 on a clean DNN 9.3.2 installation.

The installation was normal, with errors.

I installed the module on an empty page. 

I didn't try to configure the module, but it did install just fine.

**Comment by EPTamminga** [comment]
DNNReports should work without problems in DNN932
