### ISSUE TITLE
Export to excel

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/DNN.Reports#57]
Previous versions of the module had an option to "Export to Excel".
I don't see that option anymore on the settings.

Any reason why this has been removed?

**Comment by EPTamminga** [comment]
AFAIK, there never was an Excel export option in Reports. The Excel export is in the SQL host option.

**Comment by vmasanas** [comment]
See this picture:
![imagen](https://user-images.githubusercontent.com/4357679/64420850-7b179a80-d0a0-11e9-9792-e01b04a76304.png)

that is version 5.6.0

**Comment by EPTamminga** [comment]
Hmmmm.... I have to look back when that happened :-(

**Comment by EPTamminga** [comment]
I installed Reports 05.05.00, no Export to Excel. I installed Reports 05.06.00, no Export to Excel.
I looked into the sources of both. No Checkbox Export to Excel. 
![image](https://user-images.githubusercontent.com/5859855/64474646-ed0ee300-d177-11e9-8fea-3697354cac90.png)

Could it be that you are working with a modified/enhanced version of Reports? If so, do you have the source? Then I could add the Export to Excel in a new version

**Comment by vmasanas** [comment]
I dont recall having a modified version, but ill check and see what i can find.El dia 7 de set. 2019 14:01, Ernst Peter Tamminga <notifications@github.com> va escriure:I installed Reports 05.05.00, no Export to Excel.
I installed Reports 05.06.00, no Export to Excel.

Could it be that you are working with a modified/enhanced version of Reports? If so, do you have the source? Then I could add the Export to Excel in a new version

**Comment by vmasanas** [comment]
You are right, I was using a modified version and I didn't remember. I'll try to recover the code and do a pullrequest in case you are interested.

**Comment by EPTamminga** [comment]
Yes, I am interested, it is a nice enhancement. If you have modified a 5.x version, the code is probably VB.net, I converted the module to C# for 6.x.  Even so, your VB.net code is useful, I can convert that to C# as well and incorporate it in a new 6.x version

**Comment by vmasanas** [comment]
Please check https://github.com/DNNCommunity/DNN.Reports/pull/58

**Comment by EPTamminga** [comment]
Done and merged.
