### ISSUE TITLE
No install package created

### ISSUE THREAD

**Issue by ghost** [DNNCommunity/DNN.Reports#6]
I downloaded this project and was able to get it to build after I manually added a couple missing files: BuildSupport\MSBuild.Community.Tasks.dll & BuildSupport\ICSharpCode.SharpZipLib.dll. However when I build the project it creates the dll for the project but no install package was created. How do I go about installing the project without an install package? Thanks.

**Comment by EPTamminga** [comment]
I just tried the repo wit a build, and i was successful, both in the build as well as package generation. I pushed the latest changes into the development branch here, so this should work for you?
