### ISSUE TITLE
Critical error on DNN 9.50

### ISSUE THREAD

**Issue by dhassall** [DNNCommunity/DNN.Reports#66]
After install and add to page get a critical error

## Give a more extended description
Error
Error occurred when request service 'AddModule'.

I've found I have to go back to DNN 8.4.0 and Reports 5.6.0 to get going

**Comment by EPTamminga** [comment]
Please add the error log entry as documentation

**Comment by dhassall** [comment]
Hi
DNN Installed using NVQuickSite version 9.31
It in a Windows 10 PC
Thanks in advance :-)

This was the log

AbsoluteURL:

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:1b2934e0-dbf1-4595-9e64-4ff5bb3ee238

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:hhgWQGligHTr8/F5PWALGFZLKkM=

Message:Object reference not set to an instance of an object.

StackTrace:

at DotNetNuke.Modules.Reports.ReportsController.GetSearchItems(ModuleInfo ModInfo) at DotNetNuke.Services.Search.ModuleIndexer.GetSearchIndexItems(Int32 portalId)
InnerMessage:

InnerStackTrace:

Source:DotNetNuke.Modules.Reports

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: Dave-Win10

**Comment by dhassall** [comment]
Doh! clicked wrong button

**Comment by EPTamminga** [comment]
I found the problem (finally): a wrong DNN_Reports.dnn manifest file and an incomplete install pack. 
Weird, since both should have been generated automatically. Somewhere in an update, the automatic generation of a manifest and packaging has gone wrong. I will try to create a new version with a correct install pack asap. 
@dhassall: I have manually updated the 6.2.1 release with a correct install pack. Please give it a try?

**Comment by dhassall** [comment]
Thanks have downloaded and will give it a try

**Comment by dhassall** [comment]
Hi . I can confirm that this version (6.2.1) with the missing bits you added is working. I also notice on my Extensions list that it advises that 6.2.2 is avaialble but the link takes me to an error - https://dnnplatform.io/Upgrade-Link-Unavailable @EPTamminga

**Comment by EPTamminga** [comment]
Thx for the feedback,
There is no 6.2.2 yet, I think that this is an issue of DNNPlatform itself, since I also see the new version DNNPlatform 10 in my list.

**Comment by dhassall** [comment]
Hi Ernset @EPTamminga 

Nearly but not quite

I use HTML Template Vizualizer, I discovered with 6.2.1I got a large number of <br> above and below lines of data

I have removed 6.2.1 and regressed to 6.1.1 which has fixed this

Also when I choose Microsoft SQL Data Source I am unable to select the single line Connection String you have to do it item by item
![Expected](https://user-images.githubusercontent.com/42371437/76994016-ab8c9b00-6945-11ea-870a-07e368066c8b.JPG)
![LargeGaps](https://user-images.githubusercontent.com/42371437/76994019-ac253180-6945-11ea-98c7-1c8e46c15dd8.JPG)
![htmlfile](https://user-images.githubusercontent.com/42371437/76994275-09b97e00-6946-11ea-9201-fe155d8bf0ed.JPG)

Thanks

Dave

**Comment by dhassall** [comment]
Minor update, after entering the connection string long way you then get the single string

**Comment by dhassall** [comment]
Here is a work around for the Connection String enter some rubbish server 123, database A user B password C - Update
You get an error but when you go back in you have the single line string which you can now replace :-)

**Comment by dhassall** [comment]
Hi

A bit more testing

So DNN 9.5.0 "out of the box"

Add reports 6.1.0
query select top(10) tabid, tabname from Tabs

with HTML Template

< table style="width:50%" >
 < tbody>
  < tr>
    < td style="width: 5%">[tabid]
    < /td>
    < td style="width: 95%">
      [tabname]
  < /tr>
 < /tbody>
< /table>Appears fine

Upgrade to Reports 6.2.1

Now table is "exploded" with 8 < b r > (close up) above each row

**Comment by dhassall** [comment]
Hi

Done a very simple test

DNN 9.50
1 Build with Reports 6.1.0
2 Build with Reports 6.2.1

Both have the same SQL
select '12345678901234567890' as Twenty, '123456789012345678901234567890' as Thirty, '1234567890123456789012345678901234567890' as Forty

Both use the attached HTML to format the table
I put the formatting into CSS, but 6.2.1 strips the % sign whether it is put into the HTML code of the CSS
[Percent100 renametodothtml.txt](https://github.com/DNNCommunity/DNN.Reports/files/4731990/Percent100.renametodothtml.txt)

**Comment by dhassall** [comment]
Hi
Can this problem be solved with the Razor or XSL Transformation options?

Thanks

**Comment by dhassall** [comment]
Update

I was missing the quotes "w27" in the above example file
But the module was still stripping the % from the file
I took the Style information and placed it into skin.css

So now the only issue is the extra line breaks that 6.2.1 adds to each record line
See Image attached
![HTML Error Update](https://user-images.githubusercontent.com/42371437/83888819-42494680-a742-11ea-9e12-9304030e1fde.JPG)

**Comment by dhassall** [comment]
Hi

I first started using the Reports module and the HTML template a long time ago having seen the HTML template demonstrated on DNNHero.com. My knowledge of SQL was very limited and I was entering the code directly into the SQL box in the Settings and was restricted to SELECT statements.

My experience has extended and in the last 2 years my SQL knowledge expanded. I now do everything with stored procedures.

I recently discoverd extra features of SQL and used this article to produce HTML output to be used and sent via email, which is done in the Reports module. https://stackoverflow.com/questions/7070053/convert-a-sql-query-result-table-to-an-html-table-for-email/29708178

It makes little sense to develop in 2 areas i.e. SQL and HTML template. So I plan to make the SQL queries I am using include the HTML code including formatting. One added advantage, which is in the stored procedure in the above article is that if I require a Header row I can add that as well.

There is one downside and that is the HTML formatted SQL would not be useful for the Excel download, a key driver in me moving to Reports 6.2.x but the data I would be using with HTML Template I would not want to download, and anything I wanted to download would not need to be formatted.

It may seem strange but 'many thanks' this bug in 6.2.1 has made me reassess the development strategy

All the best

You can close this issue if you want to :-)

Dave

**Comment by EPTamminga** [comment]
@dhassall Thank you for your feedback. _Crisis makes creative_, we see that with the COVID-19 pandemic as well.

I will leave the issue open since I plan to solve it in a new release.

**Comment by dhassall** [comment]
Hi Ernst

Yes - hell of a year, hope things have not been bad for you.
I'm still running with the old version but would be great to have it fixed and to get the export feature
I don't know whether it was adding the Export the skewed the formatting.
For my main project I'm sticking with the previous version and looking for alternative ways to achieve the export.

**Comment by dhassall** [comment]
Hi @EPTamminga 
This is probably not an option you would like to approach, and I don't know enough about the coding to make a stab.
So 6.1.0 is great and achieves everything I want with the HTML Visualiser
So 6.2.0 is great and achieves everyting I want with exporting to Excel except it skews HTML Visualiser
For me it is a case of they would never be used together. The visualiser makes things pretty and human friendly, and the export dumps raw data.
Is it a 'simple' process to create ReportsExp so that Reports and ReportsEXP can coexist on the same DNN Platform?
No! is always an acceptable answer :-)

**Comment by EPTamminga** [comment]
@dhassall I did not take the time to have a good look.

I will have some time free from work around new year, I will put this on my todo list...

**Comment by dhassall** [comment]
Ditto. I have the 10 days off noon 24th to January 4th - catching up with a load of my personal projects too. Look forward to hearing from you.

**Comment by Tychodewaard** [comment]
Not sure if this is the same or that it should be a new issue:
The reports module works on a 9.1.1 install but throws an error on 9.7 / 9.8 and 9.9

AssemblyVersion:9.9.0
PortalId:0
UserId:974
TabId:195

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
ExceptionHash:OJzr9c4T7NriaBuDKz5sJDR6PDg=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.Reports.ReportsController.GetReport(ModuleInfo ModuleInfo)
   at DotNetNuke.Modules.Reports.ViewReports.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

**Comment by dhassall** [comment]
@Tychodewaard I do not think your issue is the same, my is specifically to do with the HTML visualizer

Indeed, in order to use export to Excel feature of Reports 6.2.x I have just created a brand new installation of DNN 9.8.1 (using nvquicksite)

6.2.0 loaded but I got an error when trying to Add a Reports module to a page
I installed 6.2.1 and everything is fine, module had been Added but would not show - now it does.

I tried DNN 9.9.0 and did have an issue so regressed one DNN version.

**Comment by EPTamminga** [comment]
@dhassall @Tychodewaard I created a pre-release version of Reports V 06.02.03, 

Have a look here: https://github.com/DNNCommunity/DNN.Reports/releases/tag/06.%2F02.03

If you could test this version and provide feedback I would be more than happy.

Please note that **this is NOT a production release of DNNReports**, do not apply this pre-release version of DNNReports on a production site, but use a test environment.

**Comment by Tychodewaard** [comment]
@EPTamminga Awesome that you take care of this module. 
- The install works fine, no errors
- Dropping the module on a page gives: _There is no data source configured for this report. Please use the Settings page for this module to configure the data source used to generate this report_
- If I try to install the plugins (select 'manage add-ins' and click on the link at the bottom of the table), this opens up a popup but that remains blank. No errors in the admin log.
![image](https://user-images.githubusercontent.com/9091997/114684756-84072e00-9d11-11eb-98e1-e371fc2055fb.png)

I tested this on the 9.9.1 beta

**Comment by EPTamminga** [comment]
@Tychodewaard Tnx for the tests & feedback 

* The first bullet (`You have to configure...`) is the **normal procedure**. You cannot start a report without a definition of the data to use and the way the result must be displayed (visualized).
* The `Manage AddIns` is **not for normal usage**, but for people who have developed Visualizers and/or Data sources plug-ins in addition to the standard ones listed. The standard ones (in the module itself) are installed by default and cannot be uninstalled. This option is **only available to HOS**T accounts (since you are able to install an extension)

I will review the code for the popup and add some clarifying text in the Manage Add-Ins.

BTW: The Wiki of Reports repo here contains documentation on how to use the module
See: https://github.com/DNNCommunity/DNN.Reports/wiki

**Comment by EPTamminga** [comment]
On second thoughts: I will remove the installation of a plug-in. 

I have been maintaining this module for many years and never encountered an unfamiliar developer with a new plug-in for DNNReports.

The additions of new plug-ins that were done in the past years were all developed by one of our active community members and included in the source of the standard module.

**Comment by EPTamminga** [comment]
@dhassall @Tychodewaard I created a new pre-release version of Reports V 06.02.03, and solved the issue that @Tychodewaard mentioned above. 

Have a look here: https://github.com/DNNCommunity/DNN.Reports/releases/tag/06.%2F02.03

This should be the new version. If you could test this version and provide feedback I would be more than happy.

Please note that **this is NOT a production release of DNNReports**, do not apply this pre-release version of DNNReports on a production site, but use a test environment.

**Comment by EPTamminga** [comment]
Solved in V 06.02.03
