### ISSUE TITLE
Submit Params by Pressing Enter

### ISSUE THREAD

**Issue by anpa8** [DNNCommunity/DNN.Reports#67]
Hi,

is it possible to have an option to Submit Params with Enter-Key?

**Comment by valadas** [comment]
Can you elaborate a bit, I am not sure what this means.

**Comment by anpa8** [comment]
When i build a report with Parameters, i would like to submit the fields with pressing enter on my keyboard, without to have to click on the Run-Button in form. (See Example: I want to enter my search string and press enter-key on keyboard, without to have to click on the "Filtern" Button)
![grafik](https://user-images.githubusercontent.com/50361933/78330479-5a56eb00-7584-11ea-9b76-671068dfaf16.png)
