### ISSUE TITLE
HTML Format ignoring formatting

### ISSUE THREAD

**Issue by dhassall** [DNNCommunity/DNN.Reports#68]
## Describe the bug
This is an extension of a report produced earlier but gives more detail and exists in 6.2.0.
I have been using the HTML visualiser for some time (years) and have recently upgraded from Reports 5.7 to Reports 6.2 because I wanted to use the Excel Export feature

## To Reproduce
In your HTML code I use Tables and set the width feature using percentage rather than px because it seems to handle moving to different devices / screen sizes

In 5.7 the HTML code 
<table style="width:100%" > works fine
but in 6.2 it strips the % so it becomes 
<table style="width:100 " > and I assume defaults to PX so what was a table that fitted the page width is now only 100px wide

Also it ignores comments
so
    

Actually takes the contents of the "comment" and places it at the statr of the table  - image attached

## Expected behavior
It should intepret the % correctly as before

## Screenshots
Attached
![HTML Error](https://user-images.githubusercontent.com/42371437/79068895-284f3280-7cc2-11ea-99a1-d30035389d15.JPG)

## Error log
Not generated.

**Comment by valadas** [comment]
The correct way to set width would be using styles such as in

```
<td style="width: 13%">
```

Can you give that a try and let us know if it fixes the issue...

If not can you post the whole template used, I am not sure I understand the link between what is described and the hightlights in the screenshot. Also I think github stripped some of your code in the description.

**Comment by dhassall** [comment]
Hi @valadas 
That seems to fix it.
I think I have some other issue with my Template because I tried it on a simpler query and that worked in both formats

I will however update my other issue as when using 6.2.1 I get extra lines

**Comment by valadas** [comment]
Well, the old way to set it as a prop on the td is deprecated but it may be supported here and there, so the safest way is to go with the styles, but it may work or not work the older way depending where.
