### ISSUE TITLE
Many extra <br> showing up when using html template visualizer

### ISSUE THREAD

**Issue by mbuelsing** [DNNCommunity/DNN.Reports#72]
DNN 8.4.0.26, Reports 6.2.1
Since I upgraded to Reports 6.2.1 I have noticed that a bunch of extra break codes are being inserted in between other tags in the finished report when using the HTML Template Visualizer and a template. This has a result of adding a bunch of extra lines in the report. I'll attach some images of the template and the resulting report.
![Template](https://user-images.githubusercontent.com/53478975/113486087-f577ee80-947e-11eb-904d-1a820691577e.png)
![ReportResults](https://user-images.githubusercontent.com/53478975/113486143-3ec83e00-947f-11eb-8a8f-3efabe0fcc8c.png)

Expected behavior: No extra break codes. How can I remove the extra codes? or How can I prevent them from being added?
Thank you for all your work on this module. I still use it many times on many sites.

**Comment by dhassall** [comment]
HI

What you are experiencing is what I reported here.. https://github.com/DNNCommunity/DNN.Reports/issues/66 (at the time badly named.)

I used the HTML template extensively for a number of sites, 

If you do not need to use the Export feature in 6.2 I would recommend you revert to 6.10

My current work around to use the export feature is I have used another domain and DNN platform to which I use an SQL query to access the data and allow it to be exported using 6.2

Hope this get's you around your issue :-)

All the best

Dave

**Comment by mbuelsing** [comment]
Dave, I appreciate your message. I read your issue. I'd actually be fine with reverting to 6.20. Can that actually be done? How? Time has passed, I would not want to restore the backup from before the upgrade. There has been a lot of development since then. Thanks so much. - Mark

**Comment by dhassall** [comment]
Hi Mark

I think the answer is "yes" - but with the usual caveats - Backup, Backup, Backup. - database and website

Step 1, just try to install 6.1.0 then check the situtation (I've had issues reverting from 6 to 5)
If failure step 2

Step 2, Go into the website files Desktop Modules / Reports on your server and delete the contents, maybe even root folder Reports.
Repeat Step 1

If you have the ability do a test on a development system. If you don't already use it NVQuickSite https://github.com/nvisionative/nvQuickSite it is an amazing resource.

If you are only using the HTML Visualiser for one Report on the site consider coding the HTML formating into the SQL query

You need some juggling to add the DIV headings if the query returns multiple lines

I've also experimented with converting my SQL Query to XML output - https://stackoverflow.com/questions/7086393/create-html-table-with-sql-for-xml.

Hope something here helps

All the best

Dave

**Comment by EPTamminga** [comment]
@dhassall @mbuelsing 

In the pre-release version of DNNReports V` 06.02.03` I also removed this bug.

Have a look here: https://github.com/DNNCommunity/DNN.Reports/releases/tag/06.%2F02.03

If you could test this version and provide feedback I would be more than happy.

Please note that **this is NOT a production release of DNNReports**, do not apply this pre-release version of DNNReports on a production site, but use a test environment.

**Comment by EPTamminga** [comment]
Solved in V 06.02.03

**Comment by dhassall** [comment]
Hi @EPTamminga 

Sorry for the delay in responding.

All seems to be fine.

Attaching 3 images

1. report 6.2.1 gaps
2. report.6.2.3 no gaps
3. reports 6.2.3 grid excel show header no

The last one shows that also fixed is the Grid View - Show Header now allows you to uncheck the box.

The query for the test was super simple
select '12345678901234567890' as Twenty, '123456789012345678901234567890' as Thirty, '1234567890123456789012345678901234567890' as Forty
union all
select '12345678901234567890' as Twenty, '123456789012345678901234567890' as Thirty, '1234567890123456789012345678901234567890' as Forty

Absolutely minor point you have to enable Show Control with Export to Excel. 

Great job is 6.2.3 Live now?
![report 6 2 1 gaps](https://user-images.githubusercontent.com/42371437/115991959-01a92480-a5c3-11eb-88d0-2ff8e96f5a53.JPG)
![report 6 2 3 no gaps](https://user-images.githubusercontent.com/42371437/115991961-0241bb00-a5c3-11eb-8b27-e5498654bd63.JPG)
![reports 6 2 3 grid excel show header no](https://user-images.githubusercontent.com/42371437/115991962-0241bb00-a5c3-11eb-99bb-69eb63aba126.JPG)

**Comment by EPTamminga** [comment]
@dhassall Thank you for the feedback. I have changed the release status into 'Release', so you should be good to go.

Fair warning: always make a backup of your running production site before installing any new version of any module.  
_Better be safe than sorry_.

Have fun!
