### ISSUE TITLE
Export to xls works but when you do Save As want to make it a Web Page

### ISSUE THREAD

**Issue by dhassall** [DNNCommunity/DNN.Reports#73]
When you export a file is downloads as an xls (not a problem) when you open it you get a warning (not a problem) but when you try to Save As to the latest version of Excel - xlsx it defaults to Web Page (*.htm) (*.html)

It's not a big problem but confuses my non-IT customers slightly.

Is there some "Microsoft Magic" going on that it knows it been downloaded from a website and therefore decides for you to default to Web Page?

**Comment by EPTamminga** [comment]
The ASP.Net framework does not have a standard option to create Excel native (.xls or .xslx) binary files. 

The programming trick is that you create a table in HTML format and save that as a file with a ".xls" extension. 
Open the file that is created with Notepad or Notepad++ and you will see it for yourself.

Excel understands that is not a binary Excel file, but opens it correctly and displays it as a .xls file. Internally, it remains an HTML text file with an extension .xls.  

When you now use `Save As`, it asks for the conversion to a real Excel binary file and AFAIK there is not an Excel setting that can change this default Excel (safety) behaviour.

A solution for the Reports module would be to use an external library to create binary Excel files directly, but we do not want to create dependability on external libraries.

Another option would be (for you/Excel) to create an Excel/VBA macro that does the Save As without asking

**Comment by WillStrohl** [comment]
What about this one, EPT?  It seems to have a lot of usage and support out there.  

https://www.nuget.org/packages/FastExcel/

**Comment by EPTamminga** [comment]
@hismightiness That MIT license code looks promising. Small footprint, not too much options, straight forward  ode, recent code updates.

I experiment a bit more to see if that is a nice replacement for the .xls/html table workaround.

Tnx for the link!

**Comment by WillStrohl** [comment]
My pleasure, sir!  😁
