### ISSUE TITLE
Multiple Allowed Url Parameters problem 

### ISSUE THREAD

**Issue by enfJoao** [DNNCommunity/DNN.Reports#9]
Hey there.

If I set "ano, mes" in "Allowed Url Parameters" I get the following error:

There was an error while executing the configured data source: There is an error in your SQL at line 1: Incorrect syntax near 'nvarchar'. Must declare the scalar variable "@url_mes".

Module bug?

Best regards,
João

**Comment by EPTamminga** [comment]
No bug, please read the documentation how you can implements URL parameters to carry forward to your SQL statement
